language: node_js

node_js:
  - "10"

env:
  - DOCKER_REPO=natnael26/udagram-api-feed

services:
  - docker

script:
 - bundle install
 - npm run build
 - docker build -t udagram-api-feed ./udagram-api-feed

after_success:
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
   docker login -u="natnael26" -p="MamiAbabi7180";
   docker push $DOCKER_REPO;
   fi