language: node_js

node_js:
  - "10"

env:
  - DOCKER_REPO=convergencelabs/javascript-examples

services:
  - docker

script:
 - bundle install
 - npm run build
 - ./scripts/docker-prepare.sh
 - docker build -t $DOCKER_REPO docker-build

after_success:
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
   docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
   docker push $DOCKER_REPO;
   fi